apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: toolbox-mount
  name: toolbox-mount
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: toolbox-mount
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: toolbox-mount
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
        operator: "Exists"
      containers:
      - image: faridsaad/tools-slim:1.02
        imagePullPolicy: IfNotPresent
        name: tools-slim
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: hostroot
          mountPath: /hostroot
      nodeSelector:
        node-role.kubernetes.io/master: ""
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hostroot
        hostPath: 
          path: /
status: {}
